# -*- coding: utf-8 -*-
"""Observatoire_tarif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEKcrAgP-eexFYlzzfBJp58z6Kc2CfgP
"""

import streamlit as st
import PyPDF2
import difflib
import pandas as pd

# Function to extract text from a PDF file
def extract_text_from_pdf(pdf_file):
    pdf_reader = PyPDF2.PdfReader(pdf_file)
    text = ""
    for page_num in range(len(pdf_reader.pages)):
        text += pdf_reader.pages[page_num].extract_text()
    return text

# Function to compare two PDFs and extract tariff changes
def compare_tariffs(pdf1_file, pdf2_file):
    # Extract text from both PDF files
    pdf1_text = extract_text_from_pdf(pdf1_file)
    pdf2_text = extract_text_from_pdf(pdf2_file)

    # Split the text into lines for better comparison (each line represents a service/tariff)
    pdf1_lines = pdf1_text.splitlines()
    pdf2_lines = pdf2_text.splitlines()

    # Find differences between the two files
    diff = difflib.unified_diff(pdf1_lines, pdf2_lines, lineterm='', n=0)

    # Separate additions (+) and deletions (-)
    additions = []
    deletions = []

    for line in diff:
        if line.startswith('+') and not line.startswith('+++'):  # Avoid the header line
            additions.append(line[1:].strip())  # Remove the '+' sign and whitespace
        elif line.startswith('-') and not line.startswith('---'):  # Avoid the header line
            deletions.append(line[1:].strip())  # Remove the '-' sign and whitespace

    return additions, deletions

# Streamlit app
st.title("Bank Tariff Comparison")

# File upload section
st.write("Upload two PDF files (from different dates) to compare tariffs:")

# Upload two PDF files
pdf1_file = st.file_uploader("Upload the first PDF file", type="pdf")
pdf2_file = st.file_uploader("Upload the second PDF file", type="pdf")

if pdf1_file is not None and pdf2_file is not None:
    # When both PDFs are uploaded, compare them
    st.write("Comparing the two PDFs...")

    # Compare the tariffs
    additions, deletions = compare_tariffs(pdf1_file, pdf2_file)

    # Create a DataFrame with two columns: "Added" and "Removed"
    max_len = max(len(additions), len(deletions))
    additions += [''] * (max_len - len(additions))  # Pad shorter list with empty strings
    deletions += [''] * (max_len - len(deletions))  # Pad shorter list with empty strings

    df = pd.DataFrame({
        'Added': additions,
        'Removed': deletions
    })

    st.write("Comparison result:")
    st.dataframe(df)  # Display the comparison result in Streamlit

    # Save the comparison result as an Excel file
    excel_file = 'tariff_comparison.xlsx'
    df.to_excel(excel_file, index=False)

    # Provide a download link for the Excel file
    with open(excel_file, 'rb') as f:
        st.download_button(
            label="Download comparison result as Excel",
            data=f,
            file_name=excel_file,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )